# Generated by Django 3.0.6 on 2020-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('showers', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('rent_period', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=60)),
                ('time_period', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-time_period'],
            },
        ),
        migrations.DeleteModel(
            name='newsArticle',
        ),
        migrations.DeleteModel(
            name='newsSite',
        ),
    ]
