# Generated by Django 3.0.6 on 2020-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0002_auto_20200530_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estates',
            name='address',
        ),
        migrations.RemoveField(
            model_name='estates',
            name='description',
        ),
        migrations.AlterField(
            model_name='estates',
            name='beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='garages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='showers',
            field=models.IntegerField(null=True),
        ),
    ]
