# Generated by Django 3.0.6 on 2020-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0005_auto_20200530_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estates',
            name='beds',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='garages',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='showers',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
