# Generated by Django 3.0.6 on 2020-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0006_auto_20200530_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estates',
            name='area',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='estates',
            name='property_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='estates',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
