# Generated by Django 3.0.6 on 2020-06-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0007_auto_20200530_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estates',
            options={'ordering': ['-time_posted']},
        ),
        migrations.RemoveField(
            model_name='estates',
            name='time_period',
        ),
        migrations.AddField(
            model_name='estates',
            name='time_posted',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='area',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='property_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='rent_period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
