# Generated by Django 3.0.6 on 2020-06-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0008_auto_20200601_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estates',
            name='beds',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='garages',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='showers',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
